# Generated by Django 4.1.5 on 2023-01-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_stripecustomer_stripesubscriptionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='setupIntentId',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
