# Generated by Django 4.1.5 on 2023-01-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_stripecustomer_setupintentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='paymentMethod',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
