# Generated by Django 4.1.5 on 2023-01-26 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_stripecustomer_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
