# Generated by Django 4.1.5 on 2023-01-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_paymentattempt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentAttempt',
        ),
    ]
