# Generated by Django 4.1.5 on 2023-01-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_paymentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='failed_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
