# Generated by Django 4.1.5 on 2023-01-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_payment_failed_and_more'),
        ('billing', '0009_paymentattempt_failed_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMemberCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('num_users', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
