# Generated by Django 4.1.5 on 2023-01-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_companymembercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.stripecustomer'),
        ),
    ]
