# Generated by Django 4.1.2 on 2022-10-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_picture/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_bio',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
