# Generated by Django 4.1.2 on 2022-10-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_picture_customuser_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_prefix',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_root',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
