# Generated by Django 4.1.2 on 2022-10-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_url_alter_company_url_root'),
        ('accounts', '0004_customuser_email_prefix_customuser_email_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('company', 'email_prefix')},
        ),
    ]
