# Generated by Django 4.1.5 on 2023-01-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_address_1_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
