# Generated by Django 4.1.2 on 2022-10-06 00:48

from django.db import migrations

def set_email_root_and_prefix(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    for user in CustomUser.objects.all():
        split_email = user.email.split('@')
        user.email_prefix = split_email[0].lower()
        user.email_root = split_email[1].lower()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_and_more'),
    ]

    operations = [migrations.RunPython(set_email_root_and_prefix, migrations.RunPython.noop)]
