# Generated by Django 4.1.5 on 2023-01-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_github_url_alter_user_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='twitter_url',
            new_name='twitter',
        ),
    ]
