# Generated by Django 4.1.6 on 2023-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_personality_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chinese_zodiac',
            field=models.CharField(blank=True, choices=[('Rat', 'Rat'), ('Ox', 'Ox'), ('Tiger', 'Tiger'), ('Rabbit', 'Rabbit'), ('Dragon', 'Dragon'), ('Snake', 'Snake'), ('Horse', 'Horse'), ('Goat', 'Goat'), ('Monkey', 'Monkey'), ('Rooster', 'Rooster'), ('Dog', 'Dog'), ('Pig', 'Pig')], max_length=240, null=True),
        ),
    ]
