# Generated by Django 4.1.6 on 2023-02-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_favourite_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_travel_destination',
            field=models.TextField(blank=True, null=True),
        ),
    ]
