# Generated by Django 4.1.6 on 2023-02-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_favourite_travel_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lon',
            new_name='lng',
        ),
    ]
