# Generated by Django 4.2.10 on 2024-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_lat_alter_user_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_or_night',
            field=models.CharField(blank=True, choices=[('Early Bird', 'Early Bird'), ('Night Owl', 'Night Owl')], max_length=240, null=True),
        ),
    ]
