# Generated by Django 4.2.10 on 2024-02-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_day_or_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet_peeves',
            field=models.TextField(blank=True, null=True),
        ),
    ]
