# Generated by Django 4.2.10 on 2024-02-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_pet_peeves'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_quote_author',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
