# Generated by Django 4.2.10 on 2024-02-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_favourite_quote_user_favourite_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_drink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
