# Generated by Django 4.2.5 on 2023-09-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_triviaquestion_created_triviaquestion_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_option', to='trivia.triviaquestion'),
        ),
    ]
