# Generated by Django 4.2.5 on 2023-09-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_alter_triviaquestionoption_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
