# Generated by Django 4.2.8 on 2023-12-21 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0025_bulkinviterequest_processed'),
        ('trivia', '0004_triviaquestion_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestionGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_generation_requests', to='companies.company')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to='trivia.triviaquestion')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trivia Question Generation Request',
                'verbose_name_plural': 'Trivia Question Generation Requests',
            },
        ),
    ]
