# Generated by Django 4.1.5 on 2023-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_failed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
