# Generated by Django 4.1.5 on 2023-01-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_payment_failed_company_payment_failed_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trial_days',
            field=models.IntegerField(default=30),
        ),
    ]
