# Generated by Django 4.1 on 2022-08-13 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_remove_company_owner_companyowner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyowner',
            options={'verbose_name': 'Company Owner', 'verbose_name_plural': 'Company Owners'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='companyowner',
            unique_together={('company', 'owner')},
        ),
    ]
