# Generated by Django 4.1 on 2022-08-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options_alter_companyowner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyowner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='companies.company'),
        ),
    ]
