# Generated by Django 4.1.1 on 2022-09-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companyowner_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url_root',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(),
        ),
    ]
