# Generated by Django 4.1.7 on 2023-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_invite_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='max_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='min_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='min_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
