# Generated by Django 4.1.7 on 2023-03-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_max_lat_alter_company_max_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='map_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
