# Generated by Django 4.1.7 on 2023-03-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_map_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='links_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
