# Generated by Django 4.1.7 on 2023-03-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_links_enabled'),
        ('companies', '0012_link'),
    ]

    operations = [
    ]
