# Generated by Django 4.1.7 on 2023-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_merge_0012_company_links_enabled_0012_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
