# Generated by Django 4.2 on 2023-04-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
