# Generated by Django 4.2 on 2023-04-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_company_billing_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='billing_disabled',
            field=models.BooleanField(default=False, help_text='Used for companies where we do not want to bill them'),
        ),
        migrations.AlterField(
            model_name='company',
            name='test_company',
            field=models.BooleanField(default=False, help_text='Used for develop testing companies'),
        ),
    ]
