# Generated by Django 4.2.2 on 2023-06-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_triviaquestion_triviaquestionoption_triviauseranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviaquestion',
            name='answer',
        ),
    ]
