# Generated by Django 4.2.5 on 2023-09-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_remove_triviaquestion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviaquestionoption',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='triviauseranswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='triviauseranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='triviauseranswer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='triviauseranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='TriviaQuestion',
        ),
        migrations.DeleteModel(
            name='TriviaQuestionOption',
        ),
        migrations.DeleteModel(
            name='TriviaUserAnswer',
        ),
    ]
