# Generated by Django 4.2.5 on 2023-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_remove_triviaquestionoption_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trivia_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
