# Generated by Django 4.2.5 on 2023-09-25 23:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_company_trivia_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
