# Generated by Django 4.2.5 on 2023-10-07 17:04

import config.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0023_alter_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkInviteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=config.storage_backends.PrivateStorage(), upload_to='bulk_invite_requests/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_invite_requests', to='companies.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_invite_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Invite Request',
                'verbose_name_plural': 'Bulk Invite Requests',
            },
        ),
    ]
