# Generated by Django 4.2.5 on 2023-10-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_bulkinviterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkinviterequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
