# Generated by Django 4.2.5 on 2023-09-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_adminemail_adminphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
