# Generated by Django 4.2.5 on 2023-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_email_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='downloadable_files/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
